### ISSUE TITLE
Write the HTTPS section

### ISSUE THREAD

**Issue by mxsasha** [mxsasha/nrtmv4#10]
This is currently empty. I don't really know much except "normal reasonable HTTPS with reasonable certificate validation". Maybe we can borrow from RRDP?

**Comment by job** [comment]
Don't borrow from RRDP in this regard, the RRDP spec is special in this aspect in that there is an underlaying assumption about "object security".

I recommend simply referencing BCP 195 / RFC 7525 "Recommendations for Secure Use of Transport Layer Security (TLS)"

**Comment by stkonst** [comment]
I don't have much experiences with that subject so I will stay neutral and go with the flow.

**Comment by mxsasha** [comment]
> I recommend simply referencing BCP 195 / RFC 7525 "Recommendations for Secure Use of Transport Layer Security (TLS)"

Sounds good. As it's a single sentence, I pushed it already in 79aae27.
