### ISSUE TITLE
Mention local file imports?

### ISSUE THREAD

**Issue by mxsasha** [mxsasha/nrtmv4#11]
We focus on HTTPS as a distribution mechanism, but sometimes people will import from local files, and IRRD will support that. It's not a main use case, but we should probably mention it?

Thinking it should only work for a full repo, i.e. including signature, just skipping the HTTPS part.

**Comment by job** [comment]
I think it is good to mention this deployment aspect

**Comment by stkonst** [comment]
Just to ensure that I understand correctly: by 'local file imports' you mean to inject extra objects to mirror server that do not officially exist in IRRdb ?

**Comment by job** [comment]
@stkonst "local file imports" means (for example) that you have a `wget` + `irrd_load_database` in a `cron` job, instead of using NRTM. The concept of "local file imports" has nothing to do whether something officially exists or not, merely another transport mechanism other than NRTM.

**Comment by stkonst** [comment]
Hi @job thank's for the clarification. Perhaps we can have under the "Operational Considerations" chapter a section that includes this and other deployment scenarios that come to our minds.
