### ISSUE TITLE
Base64 for object encoding?

### ISSUE THREAD

**Issue by mxsasha** [mxsasha/nrtmv4#12]
Should we encode the RPSL object text as base64? Job suggested this. Makes it bigger, but may reduce encoding issues, as the XML can now fit in ASCII. Of course, you still need to decode it as UTF-8 later.

**Comment by job** [comment]
I think the choice is to either encode as base64, or wrap the entire message in a binary encoding like DER. (the latter option meaning that in practise you have 'direct' access to the objects, because the files will be 'mostly' visible with tools like `cat` or `strings`.

**Comment by stkonst** [comment]
Another topic that I would like to be neutral. To be honest I hate encoding issues and always have troubles with that subject, thus even If you like to keep it simple and propose to use ASCII I would be happy with it (plus the benefit of using ASCII is that no strange characters can be encoded/transferred). If there are strong benefits of going with base64 then I will support you guys.

**Comment by mxsasha** [comment]
I do think we need UTF-8 support, because different IRR databases already use different non-ASCII encodings. I see the benefit of having somewhat human readable objects though. I am having trouble with figuring out DER encoding. Perhaps a simpler approach would be quoted-printable? No change to human readability of 7-bit ASCII text.

I'll put quoted-printable in the draft, but of course it's trivial to change to base64 later if discussion goes that way.
