### ISSUE TITLE
Check sample URLs and other details from examples

### ISSUE THREAD

**Issue by mxsasha** [mxsasha/nrtmv4#13]
The URLs in the examples, and other data in there, should be good choices, as they may be closely followed by implementations.

**Comment by job** [comment]
Good point, we probably should learn a lesson from this observation https://mailarchive.ietf.org/arch/msg/sidrops/b34pFFmmTio1EJbZYJegBm-ULFI/

**Comment by stkonst** [comment]
I can help on aligning the URLs and the data included in the examples :) 
Do you mind if I use AMS-IX numbers/IPs/ASNs etc etc ?

**Comment by job** [comment]
We should use example.net and the IETF documentation IPs

**Comment by stkonst** [comment]
Ok super, even better...
