### ISSUE TITLE
Handle slightly outdated UNF gracefully

### ISSUE THREAD

**Issue by mxsasha** [mxsasha/nrtmv4#36]
Scenario:
* Server publishes new UNF version 22 with new delta, all valid.
* Server pushes this to CDN.
* Client updates to this version. 
* CDN has slow synchronisation, so not all nodes have latest update yet - some still have the v21 UNF.
* Client updates again, hits different node, gets version 21 UNF.

I think the current implementation in IRRD consistent with the current text says: UNF invalid, reset session. I think this should have more grace. Particularly with #33 allowing us to detect real history rewrites.

Suggestion: when clients find an otherwise valid UNF with one version lower than the current client version, it should do nothing. No changes, no updates, just ignore and check again in a minute. More than one version behind -> reset.

Credit to Tim Bruijnzeels for raising this at RIPE88.

**Comment by job** [comment]
This is the way

**Comment by stkonst** [comment]
I do agree that if a client detects a UNF with lower version, then he should simply ignore it. 

Shall we update section 5.2 with this recommendation? 

Also, shall we include a recommendation that if client detects a session_id mismatch then it must immediately reset ?

**Comment by mxsasha** [comment]
Made #37 for this. We did already cover this more than I thought, it is a reject, not a reset, if the UNF matches. Still, added a recommendation on the difference between small offset and large offset. 

> Also, shall we include a recommendation that if client detects a session_id mismatch then it must immediately reset ?

That's already in there.
