### ISSUE TITLE
FInalise some terminology

### ISSUE THREAD

**Issue by mxsasha** [mxsasha/nrtmv4#4]
* Mirror server / mirror client may not be the most optimal names, but the
  best I have so far.
* We now consistently use the term "RPSL objects" - in earlier versions this
  was a mix of "IRR objects" and "RPSL objects". Good wording?

Unless someone contributes something better, I think we're sticking with these.

**Comment by job** [comment]
Let's call them RPSL objects

**Comment by stkonst** [comment]
I vote for "IRR objects" simply because we don't care in which language the objects are written. Today is RPSL, tomorrow something else.

**Comment by mxsasha** [comment]
As NRTMv4 is fairly agnostic to objects being RPSL, I also like IRR objects a bit more. I'll change it, we can always refine this one later if there is more discussion.
