### ISSUE TITLE
Figure out how to detect stale repositories

### ISSUE THREAD

**Issue by mxsasha** [mxsasha/nrtmv4#5]
If we only publish Snapshot Files and Delta Files when data changes, i.e. nothing happens if there is no change, how do people distinguish a stale publication point from a server that has had no changes?

Some IRRs are very quiet. But stale repository detection, even if only by humans, is important. People may leave old endpoints lying around with stale data.

First thought: give the Update Notification File a generation timestamp and require a regeneration and re-signing daily or so? Only if it was not already regenerated for another reason, i.e. new Snapshot File or Delta File.

**Comment by stkonst** [comment]
I agree with the idea of having the generation timestamp included. Also the generation of a Snapshot file every 24h is a good practice and can help the clients to detect if the mirror server is in stale state or it was generally quiet. 

However I want to point out that in case that the generation of the snapshot file happens every day at the same time e.g. 12:01 sharp, then there is a danger that we will have a big overload of queries at 12:01:01 from mirror clients.

**Comment by mxsasha** [comment]
> However I want to point out that in case that the generation of the snapshot file happens every day at the same time e.g. 12:01 sharp, then there is a danger that we will have a big overload of queries at 12:01:01 from mirror clients.

I don't see this. Clients will fetch the update notification file regularly anyways. Merely updating a timestamp in there does not trigger additional requests. And publishing a new snapshot does not trigger requests a snapshot download clients who have been following the deltas.

I'll write a PR.
