### ISSUE TITLE
Consider metadata in delta/snapshot files

### ISSUE THREAD

**Issue by mxsasha** [mxsasha/nrtmv4#7]
In the delta and/or snapshot files, we could add space for metadata. What kind of data is useful there? IRRd has, for each individual object change, the reason for the change and a unique serial, which might help in tracing. This might depend on individual implementations.

**Comment by job** [comment]
Perhaps

* a set of counters on the number of objects added/removed in a given snapshot or delta?
* set of counters about how many objects in which class
* A generation timestamp, and perhaps time elapsed to generate the file
* hostname of the machine that generated the file

**Comment by stkonst** [comment]
A counter like how many times this object has been updated within the X amount of time is something useful.
Also the amount of days until the key will rotate would be useful. 

But I believe that once the draft goes out for public review we would have more suggestions on that subject. However, is good that the option exists to accommodate future needs.

**Comment by sumkincpp** [comment]
Timestamp for deltas are very useful - one can check if it's local snapshot up-to-date based on it's value.

Though, the latest timestamp in notification file should probably match the timestamp for the latest delta.

**Comment by mxsasha** [comment]
Discussed at RIPE88: we will add a place for metadata in the UNF to aid in debugging.

**Comment by mxsasha** [comment]
PR in #38
